### ISSUE TITLE
Modified workflow to use flowVS-transformed FCS in Spectre clustering workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [HdBraanker/Spectral_Flow_Workflow#3]
Hi there, 

Thanks again for this workflow. 

I aim to use flowVS to determine the optimum cofactor per channel and check the transformed data, following your detailed workflow (https://github.com/HdBraanker/Spectral_Flow_Workflow/blob/main/script.Rmd). 

I now want to use these transformed FCS files in the Spectre package, so I:
1. Exported the transformed flowSet object as FCS files.
3. Used these FCS as input to the Spectre package, skipping all of the arcsinh transformation steps and proceed straight to adding the metadata (https://immunedynamics.io/spectre/simple-discovery/#2_Import_and_prep_data)

Would you mind informing me whether these steps/codes make sense? Or is there more efficient way to do this?

Thank you.

```
## All previous steps are the same as https://github.com/HdBraanker/Spectral_Flow_Workflow/blob/main/script.Rmd
## Transform channels in all samples with arcsinh 
concat_fcs_data_fcs_transform <- transFlowVS(concat_fcs_data, channels = concat_fcs_data_markerstotransform, concat_fcs_data_small_cofactors)
concat_fcs_data_filenames <- sampleNames(concat_fcs_data)
sampleNames(concat_fcs_data_fcs_transform) <- concat_fcs_data_filenames

## Export transformed flowSet object as FCS files
concat_fcs_data_fcs_transform_outdir <- file.path("...", "concat_fcs_data_fcs_transform")
concat_fcs_data_fcs_transform_filenames <- paste("flowVSTransformed_",concat_fcs_data@phenoData@data$name)
write.flowSet(concat_fcs_data_fcs_transform, outdir = concat_fcs_data_fcs_transform_outdir, filename = concat_fcs_data_fcs_transform_filenames)

#Input transformed FCS to Spectre and start at Step 4. Add metadata
```

**Comment by HdBraanker** [comment]
Hi,

There might be a shorter way, but this looks good and we would have done it
the same!

Good luck analysing!

Op do 19 jan. 2023 om 16:34 schreef Quang Nguyen ***@***.***>
